import 'package:flutter/material.dart';
import '../models/admin_data.dart';
import '../models/operations_data.dart';

// ═══════════════════════════════════════════════════════════════
//  EMPLOYEE STORAGE ASSIGNMENT — §7.1 step 4
//  • Receive storage instructions generated by AI agent
//  • Instructions specify exact floor and slot location
//  • Transport products to assigned storage area
//  • Validate storage completion in the system
// ═══════════════════════════════════════════════════════════════

class EmpStorageScreen extends StatefulWidget {
  final List<OperationalTask> tasks;
  final VoidCallback onTaskUpdated;

  const EmpStorageScreen({super.key, required this.tasks, required this.onTaskUpdated});

  @override
  State<EmpStorageScreen> createState() => _EmpStorageScreenState();
}

class _EmpStorageScreenState extends State<EmpStorageScreen> {
  List<OperationalTask> get _transferTasks =>
      widget.tasks.where((t) => t.operation == OpType.transfer).toList();

  @override
  Widget build(BuildContext context) {
    final tasks = _transferTasks;

    return Padding(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // ── Header ──
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(10),
                decoration: BoxDecoration(
                  color: OpType.transfer.color.withValues(alpha: 0.12),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Icon(OpType.transfer.icon, color: OpType.transfer.color, size: 24),
              ),
              const SizedBox(width: 12),
              const Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text('Storage Assignment', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w700, color: AppColors.textDark)),
                    Text('Transfer products to storage locations', style: TextStyle(fontSize: 12, color: AppColors.textMid)),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),

          // ── AI Assignment Banner ──
          Container(
            padding: const EdgeInsets.all(10),
            decoration: BoxDecoration(
              color: const Color(0xFFFFF3E0),
              borderRadius: BorderRadius.circular(10),
              border: Border.all(color: const Color(0xFFFFCC80)),
            ),
            child: const Row(
              children: [
                Icon(Icons.smart_toy_rounded, color: Color(0xFFE65100), size: 18),
                SizedBox(width: 8),
                Expanded(
                  child: Text(
                    'Storage locations are AI-assigned. Floor & slot specified for each task.',
                    style: TextStyle(fontSize: 11, color: Color(0xFFE65100), fontWeight: FontWeight.w500),
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 16),

          // ── Task List ──
          Expanded(
            child: tasks.isEmpty
                ? const Center(child: Text('No transfer tasks assigned.', style: TextStyle(color: AppColors.textMid)))
                : ListView.builder(
                    itemCount: tasks.length,
                    itemBuilder: (_, i) => _buildTransferCard(tasks[i]),
                  ),
          ),
        ],
      ),
    );
  }

  Widget _buildTransferCard(OperationalTask task) {
    final isCompleted = task.status == OpTaskStatus.completed;
    final isActive = task.status == OpTaskStatus.inProgress;

    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: isActive
              ? OpType.transfer.color.withValues(alpha: 0.4)
              : isCompleted
                  ? AppColors.success.withValues(alpha: 0.3)
                  : AppColors.divider,
        ),
      ),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // ── Header Row ──
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                  decoration: BoxDecoration(
                    color: OpType.transfer.color.withValues(alpha: 0.1),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Text(task.orderRef, style: TextStyle(fontSize: 12, fontWeight: FontWeight.w700, color: OpType.transfer.color)),
                ),
                const Spacer(),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                  decoration: BoxDecoration(
                    color: task.status.color.withValues(alpha: 0.12),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Text(task.status.label, style: TextStyle(fontSize: 10, fontWeight: FontWeight.w700, color: task.status.color)),
                ),
              ],
            ),
            const SizedBox(height: 12),

            // ── Product ──
            Text(task.productName, style: const TextStyle(fontSize: 15, fontWeight: FontWeight.w600, color: AppColors.textDark)),
            const SizedBox(height: 4),
            Text('${task.sku} · ${task.expectedQuantity} units', style: const TextStyle(fontSize: 12, color: AppColors.textMid)),
            const SizedBox(height: 12),

            // ── Route: From → To with floor info ──
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: AppColors.bg,
                borderRadius: BorderRadius.circular(12),
              ),
              child: Row(
                children: [
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text('FROM', style: TextStyle(fontSize: 9, fontWeight: FontWeight.w700, color: AppColors.textLight, letterSpacing: 1)),
                        const SizedBox(height: 4),
                        Row(
                          children: [
                            const Icon(Icons.location_on_rounded, size: 14, color: AppColors.error),
                            const SizedBox(width: 4),
                            Text(task.fromLocation, style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w600)),
                          ],
                        ),
                      ],
                    ),
                  ),
                  const Padding(
                    padding: EdgeInsets.symmetric(horizontal: 8),
                    child: Icon(Icons.arrow_forward_rounded, size: 20, color: AppColors.textMid),
                  ),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text('TO', style: TextStyle(fontSize: 9, fontWeight: FontWeight.w700, color: AppColors.textLight, letterSpacing: 1)),
                        const SizedBox(height: 4),
                        Row(
                          children: [
                            const Icon(Icons.location_on_rounded, size: 14, color: AppColors.success),
                            const SizedBox(width: 4),
                            Flexible(child: Text(task.toLocation, style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w600))),
                          ],
                        ),
                      ],
                    ),
                  ),
                  Container(
                    padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                    decoration: BoxDecoration(
                      color: AppColors.primaryDark.withValues(alpha: 0.1),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Text(
                      'Floor ${task.targetFloor}',
                      style: const TextStyle(fontSize: 10, fontWeight: FontWeight.w700, color: AppColors.primaryDark),
                    ),
                  ),
                ],
              ),
            ),

            if (task.assignedChariotId.isNotEmpty) ...[
              const SizedBox(height: 8),
              Row(
                children: [
                  const Icon(Icons.shopping_cart_outlined, size: 14, color: AppColors.textMid),
                  const SizedBox(width: 4),
                  Text('Assigned: ${task.assignedChariotId}', style: const TextStyle(fontSize: 11, color: AppColors.textMid)),
                ],
              ),
            ],

            if (!isCompleted) ...[
              const SizedBox(height: 14),
              Row(
                children: [
                  if (task.status == OpTaskStatus.pending)
                    Expanded(
                      child: FilledButton.icon(
                        onPressed: () {
                          setState(() {
                            task.status = OpTaskStatus.inProgress;
                            task.startedAt = DateTime.now();
                          });
                          widget.onTaskUpdated();
                        },
                        icon: const Icon(Icons.play_arrow_rounded, size: 18),
                        label: const Text('Start Transfer'),
                        style: FilledButton.styleFrom(
                          backgroundColor: OpType.transfer.color,
                          padding: const EdgeInsets.symmetric(vertical: 12),
                        ),
                      ),
                    ),
                  if (task.status == OpTaskStatus.inProgress)
                    Expanded(
                      child: FilledButton.icon(
                        onPressed: () => _validateStorage(task),
                        icon: const Icon(Icons.check_rounded, size: 18),
                        label: const Text('Validate Storage'),
                        style: FilledButton.styleFrom(
                          backgroundColor: AppColors.success,
                          padding: const EdgeInsets.symmetric(vertical: 12),
                        ),
                      ),
                    ),
                ],
              ),
            ],

            if (isCompleted) ...[
              const SizedBox(height: 10),
              Container(
                padding: const EdgeInsets.all(10),
                decoration: BoxDecoration(
                  color: AppColors.success.withValues(alpha: 0.08),
                  borderRadius: BorderRadius.circular(10),
                ),
                child: const Row(
                  children: [
                    Icon(Icons.check_circle_rounded, size: 18, color: AppColors.success),
                    SizedBox(width: 8),
                    Text('Storage completed & validated', style: TextStyle(fontSize: 12, color: AppColors.success, fontWeight: FontWeight.w600)),
                  ],
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }

  void _validateStorage(OperationalTask task) {
    setState(() {
      task.status = OpTaskStatus.completed;
      task.completedAt = DateTime.now();
      task.receivedQuantity = task.expectedQuantity;
    });
    widget.onTaskUpdated();
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text('Transfer ${task.orderRef} completed — stored at ${task.toLocation}.'),
        backgroundColor: AppColors.success,
      ),
    );
  }
}
